spring.datasource.url=jdbc:postgresql://neondb_owner:npg_vKOi3BFeu1Rw@ep-still-brook-amdhs7v4-pooler.c-5.us-east-1.aws.neon.tech/data?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_vKOi3BFeu1Rw
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
